### ISSUE TITLE
Cinder driver starting for pure storage backends in openstack branch

### ISSUE THREAD

**Issue by ccrow42** [puresealab/newstack_testdrive#2]
```
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager [None req-ff66cdc5-26c5-4167-840b-b8a02b89fe06 None None] Failed to initialize driver.: PureHTTPError: PureHTTPError status code 400 returned by REST version 1.14 at 10.0.1.76: BAD REQUEST
Jun 28 21:56:58 linux cinder-volume[14844]: [{"msg": "Target array could not be found.", "ctx": "FA2"}]
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager Traceback (most recent call last):
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/opt/stack/cinder/cinder/volume/manager.py", line 467, in _init_host
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     self.driver.do_setup(ctxt)
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/opt/stack/cinder/cinder/volume/drivers/pure.py", line 343, in do_setup
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     self.do_setup_replication()
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/opt/stack/cinder/cinder/volume/drivers/pure.py", line 378, in do_setup_replication
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     self._async_replication_retention_policy
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/opt/stack/cinder/cinder/volume/drivers/pure.py", line 175, in wrapper
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     result = f(*args, **kwargs)
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/opt/stack/cinder/cinder/volume/drivers/pure.py", line 2024, in _setup_replicated_pgroups
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     "pgname": pg_name})
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     self.force_reraise()
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     six.reraise(self.type_, self.value, self.tb)
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/opt/stack/cinder/cinder/volume/drivers/pure.py", line 2013, in _setup_replicated_pgroups
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     addtargetlist=[target_array.array_name])
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/purestorage/purestorage.py", line 3012, in set_pgroup
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     return self._request("PUT", "pgroup/{0}".format(pgroup), kwargs)
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/opt/stack/cinder/cinder/volume/drivers/pure.py", line 1477, in wrapper
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     ret = fn(*args, **kwargs)
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/purestorage/purestorage.py", line 202, in _request
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager     raise PureHTTPError(self._target, str(self._rest_version), response)
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager PureHTTPError: PureHTTPError status code 400 returned by REST version 1.14 at 10.0.1.76: BAD REQUEST
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager [{"msg": "Target array could not be found.", "ctx": "FA2"}]
Jun 28 21:56:58 linux cinder-volume[14844]: ERROR cinder.volume.manager 
Jun 28 21:56:59 linux cinder-volume[14844]: INFO cinder.volume.manager [None req-ff66cdc5-26c5-4167-840b-b8a02b89fe06 None None] Starting volume driver PureISCSIDriver (9.0.0)
Jun 28 21:56:59 linux cinder-volume[14844]: WARNING py.warnings [None req-ff66cdc5-26c5-4167-840b-b8a02b89fe06 None None] /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Jun 28 21:56:59 linux cinder-volume[14844]: InsecureRequestWarning)
```

**Comment by ccrow42** [comment]
There was a cinder config error as well as a host of other bug fixes that removed this issue.
